apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: pod-viewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pod-viewer-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-viewer-role
subjects:
- kind: ServiceAccount
  name: pod-viewer
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-viewer
  name: pod-viewer
spec:
  containers:
  - image: bitnami/kubectl
    name: pod-viewer
    command: ["sleep", "3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  serviceAccountName: pod-viewer
  restartPolicy: Always
status: {}
---