apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kubectl
  name: kubectl
spec:
  containers:
  - image: bitnami/kubectl
    name: kubectl
    command: 
    - sleep
    args:
    - '9000'
    resources: {}
  dnsPolicy: ClusterFirst
  # serviceAccount: permissions
  restartPolicy: Always
status: {}

