apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx:1.18.0
      name: nginx
      resources:
        requests:
          cpu: "0.5"
          memory: "512m"
        limits:
          cpu: "1"
          memory: "1024m"