apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web
    env: dev
  name: label-pod
spec:
  containers:
  - image: nginx
    name: label-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
